import { PendingSubmitButton } from "@/components/feedback/PendingSubmitButton";
import { createClient } from "@/lib/supabase/server";
import { createAccessProduct, createReferralCode, toggleAccessProduct } from "./actions";

type Product = { id: string; name: string; slug: string; price_inr: number; duration_days: number; is_active: boolean; access_product_exam_groups: { exam_groups: { name: string } | null }[] | null };

export default async function AdminAccessPage() {
  const supabase = await createClient();
  const [groupsResult, productsResult, referralResult] = await Promise.all([
    supabase.from("exam_groups").select("id, name, exams(name)").order("display_order"),
    supabase.from("access_products").select("id, name, slug, price_inr, duration_days, is_active, access_product_exam_groups(exam_groups(name))").order("display_order"),
    supabase.from("referral_codes").select("id, code, discount_type, discount_value, is_active, access_products(name)").order("created_at", { ascending: false }).limit(25),
  ]);
  const products = (productsResult.data ?? []) as unknown as Product[];
  return <div><p className="text-xs font-black uppercase tracking-[0.14em] text-teal-700">Payments and access</p><h1 className="mt-2 text-3xl font-black">Exam Passes</h1><p className="mt-2 max-w-3xl text-slate-600">A pass unlocks every paid Mock Test under the selected Exam. Access is granted only after the payment status is verified on the server.</p>
    <section className="mt-8 grid gap-8 xl:grid-cols-[1fr_1.1fr]"><form action={createAccessProduct} className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Create Exam Pass</h2><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Pass name<input required name="name" className="mt-1.5 w-full rounded-xl border px-3 py-2.5" placeholder="Telangana Police Constable Pass" /></label><label className="text-sm font-bold">URL label (optional)<input name="slug" className="mt-1.5 w-full rounded-xl border px-3 py-2.5" placeholder="telangana-police-constable-pass" /></label><label className="text-sm font-bold">Description<textarea name="description" className="mt-1.5 min-h-20 w-full rounded-xl border px-3 py-2.5" /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">Price (₹)<input required min="0" step="1" type="number" name="price_inr" className="mt-1.5 w-full rounded-xl border px-3 py-2.5" /></label><label className="text-sm font-bold">Valid days<input required min="1" type="number" name="duration_days" defaultValue="90" className="mt-1.5 w-full rounded-xl border px-3 py-2.5" /></label></div><label className="text-sm font-bold">Exams covered<select required multiple name="exam_group_ids" className="mt-1.5 min-h-32 w-full rounded-xl border px-3 py-2.5">{(groupsResult.data ?? []).map((group) => <option key={group.id} value={group.id}>{(group.exams as unknown as { name: string } | null)?.name ?? "Category"} · {group.name}</option>)}</select><span className="mt-1 block text-xs font-normal text-slate-500">Hold Ctrl (or Cmd) to select more than one exam.</span></label><PendingSubmitButton pendingLabel="Creating pass…" className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-60">Create Exam Pass</PendingSubmitButton></div></form>
      <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Existing passes</h2><div className="mt-5 grid gap-3">{products.map((product) => <div key={product.id} className="rounded-2xl border bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black">{product.name}</p><p className="mt-1 text-sm text-slate-600">₹{Number(product.price_inr).toFixed(0)} · {product.duration_days} days · {product.access_product_exam_groups?.map((item) => item.exam_groups?.name).filter(Boolean).join(", ")}</p></div><form action={toggleAccessProduct}><input type="hidden" name="id" value={product.id} /><input type="hidden" name="active" value={String(product.is_active)} /><PendingSubmitButton pendingLabel="Updating…" className="rounded-lg border px-3 py-2 text-xs font-bold">{product.is_active ? "Pause sales" : "Activate"}</PendingSubmitButton></form></div></div>)}{!products.length && <p className="text-sm text-slate-600">No Exam Passes created yet.</p>}</div></section></section>
    <section className="mt-8 grid gap-8 xl:grid-cols-[1fr_1.1fr]"><form action={createReferralCode} className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Referral code</h2><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Code<input required name="code" maxLength={40} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 uppercase" placeholder="POLICE10" /></label><label className="text-sm font-bold">Pass (optional)<select name="product_id" className="mt-1.5 w-full rounded-xl border px-3 py-2.5"><option value="">Any pass</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">Benefit<select name="discount_type" className="mt-1.5 w-full rounded-xl border px-3 py-2.5"><option value="percent">Percentage off</option><option value="amount">₹ off</option><option value="free_pass">Free pass</option><option value="bonus_days">Bonus days</option></select></label><label className="text-sm font-bold">Value<input name="discount_value" type="number" min="0" step="1" defaultValue="0" className="mt-1.5 w-full rounded-xl border px-3 py-2.5" /></label></div><label className="text-sm font-bold">Maximum uses (optional)<input name="max_redemptions" type="number" min="1" className="mt-1.5 w-full rounded-xl border px-3 py-2.5" /></label><PendingSubmitButton pendingLabel="Creating code…" className="rounded-xl bg-teal-700 px-5 py-3 text-sm font-black text-white disabled:opacity-60">Create referral code</PendingSubmitButton></div></form><section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Recent referral codes</h2><div className="mt-5 grid gap-3">{(referralResult.data ?? []).map((code) => <div key={code.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-mono font-black">{code.code}</p><p className="mt-1 text-sm text-slate-600">{code.discount_type.replace("_", " ")} · {code.discount_value} · {(code.access_products as unknown as { name: string } | null)?.name ?? "Any pass"}</p></div>)}{!(referralResult.data ?? []).length && <p className="text-sm text-slate-600">No referral codes created yet.</p>}</div></section></section>
  </div>;
}
