import type { Metadata } from "next";
import Link from "next/link";
import { PublicHeader } from "@/components/site/PublicHeader";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Terms and Conditions for using Varadhi Prep mock tests and paid exam series.",
  alternates: { canonical: "/terms-and-conditions" },
};

const updated = "25 August 2026";

export default function TermsAndConditionsPage() {
  return <main className="min-h-screen bg-slate-50 text-slate-950"><PublicHeader compact /><section className="mx-auto max-w-3xl px-5 py-14 sm:px-8 sm:py-20"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">Varadhi Prep policies</p><h1 className="font-display mt-3 text-3xl tracking-tight sm:text-4xl">Terms and Conditions</h1><p className="mt-3 text-sm text-slate-500">Last updated: {updated}</p><div className="mt-8 space-y-7 text-sm leading-7 text-slate-700"><section><h2 className="text-lg font-black text-slate-950">1. Our service</h2><p className="mt-2">Varadhi Prep provides online practice mock tests, question reviews and exam-series access for students preparing for competitive examinations. It is a study and practice service; it does not represent or guarantee selection, employment, examination results or affiliation with any recruiting authority.</p></section><section><h2 className="text-lg font-black text-slate-950">2. Student accounts</h2><p className="mt-2">Keep your login details private and use your own account. Do not share paid access, copy paid content for redistribution, attempt to bypass access controls, or interfere with the platform.</p></section><section><h2 className="text-lg font-black text-slate-950">3. Free and paid mock tests</h2><p className="mt-2">Free mock tests can be accessed according to the platform rules. A paid Exam Series gives the purchasing student access to the paid mock tests covered by that series for the displayed validity period. Included exams, price and validity are shown before payment.</p></section><section><h2 className="text-lg font-black text-slate-950">4. Payments and pricing</h2><p className="mt-2">All paid Exam Series prices are displayed in Indian Rupees (INR). Payments are processed through our payment partner, Cashfree. Access is granted only after payment is successfully verified on our server.</p></section><section><h2 className="text-lg font-black text-slate-950">5. Availability and changes</h2><p className="mt-2">We work to keep the service available and accurate, but may update mock tests, questions, features, prices or these terms when needed. Material changes to an active paid purchase will not remove already granted access before its stated expiry unless required for security, law or misuse prevention.</p></section><section><h2 className="text-lg font-black text-slate-950">6. Support</h2><p className="mt-2">For account, payment or study-platform help, contact us at <a className="font-bold text-teal-700 underline" href="mailto:support@varadhiprep.in">support@varadhiprep.in</a>. Our Refunds and Cancellations policy explains payment-related requests.</p></section></div><div className="mt-10 border-t pt-6"><Link href="/refunds-and-cancellations" className="font-bold text-teal-700 underline">Read Refunds and Cancellations →</Link></div></article></section></main>;
}
