import type { Metadata } from "next";
import Link from "next/link";
import { PublicHeader } from "@/components/site/PublicHeader";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Varadhi Prep collects, uses and protects student account and study data.",
  alternates: { canonical: "/privacy-policy" },
};

const updated = "27 August 2026";

export default function PrivacyPolicyPage() {
  return <main className="min-h-screen bg-slate-50 text-slate-950"><PublicHeader compact /><section className="mx-auto max-w-3xl px-5 py-14 sm:px-8 sm:py-20"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-black uppercase tracking-[0.16em] text-teal-700">Varadhi Prep policies</p><h1 className="font-display mt-3 text-3xl tracking-tight sm:text-4xl">Privacy Policy</h1><p className="mt-3 text-sm text-slate-500">Last updated: {updated}</p><div className="mt-8 space-y-7 text-sm leading-7 text-slate-700"><section><h2 className="text-lg font-black text-slate-950">1. Information we collect</h2><p className="mt-2">When you create an account, we collect your name, email address and, if you provide it, mobile number. We also keep the mock tests you start, your answers, scores, saved progress and question reports so that the study service works correctly.</p></section><section><h2 className="text-lg font-black text-slate-950">2. Google sign-in</h2><p className="mt-2">If you choose Continue with Google, Google shares the basic profile information you approve, such as your name and email address. We use this only to create and secure your Varadhi Prep account. Google sign-in does not provide your mobile number; we ask for it separately only when it is needed for payment or account details.</p></section><section><h2 className="text-lg font-black text-slate-950">3. How we use information</h2><p className="mt-2">We use account and study data to provide mock tests, show results and progress, protect accounts, provide support, process Exam Series access and improve the platform. We do not sell your personal information.</p></section><section><h2 className="text-lg font-black text-slate-950">4. Payments</h2><p className="mt-2">Payments are handled by our payment partner, Cashfree. We receive payment status and purchase references needed to grant access; we do not store your card or UPI credentials.</p></section><section><h2 className="text-lg font-black text-slate-950">5. Storage and security</h2><p className="mt-2">We use service providers to host the website, authenticate accounts, store study data and send service emails. Access is restricted to people and systems that need it to operate Varadhi Prep. No online service can guarantee absolute security, but we use reasonable safeguards to protect your information.</p></section><section><h2 className="text-lg font-black text-slate-950">6. Your choices and contact</h2><p className="mt-2">You may contact us to ask about your account information or request help. For privacy, account or payment questions, email <a className="font-bold text-teal-700 underline" href="mailto:support@varadhiprep.in">support@varadhiprep.in</a>.</p></section></div><div className="mt-10 border-t pt-6"><Link href="/terms-and-conditions" className="font-bold text-teal-700 underline">Read Terms and Conditions →</Link></div></article></section></main>;
}
