import type { Metadata } from "next";
import { notFound, permanentRedirect } from "next/navigation";
import MockTestsPage, { type Filters } from "@/app/mock-tests/page";
import { JsonLd } from "@/components/seo/JsonLd";
import { resolvePublicRoute } from "@/lib/public-route-data";
import { collectionStructuredData, isIndexableCollectionQuery, publicCollectionMetadata } from "@/lib/public-seo";
import { examUrl, paperUrl, stateUrl } from "@/lib/public-urls";
import { resolveSeoFields } from "@/lib/seo-fields";
type Props = { params: Promise<{ id: string; exam: string; paper: string }>; searchParams: Promise<Filters> };
export async function generateMetadata({ params, searchParams }: Props): Promise<Metadata> { const p = await params; const c = await resolvePublicRoute({ stateSlug: p.id, examSlug: p.exam, paperSlug: p.paper }); if (!c?.exam || !c.paper) return { title: "Paper Not Found", robots: { index: false, follow: false } }; const canonical = paperUrl(c.state.slug, c.exam.slug, c.paper.slug); const seo = resolveSeoFields(c.paper, { title: `${c.exam.name} ${c.paper.name} Mock Tests`, description: `Take free ${c.paper.name} mock tests for ${c.exam.name} in ${c.state.name}.` }); return publicCollectionMetadata({ ...seo, canonical, indexable: isIndexableCollectionQuery(await searchParams) }); }
export default async function PaperPage({ params, searchParams }: Props) { const p = await params; const c = await resolvePublicRoute({ stateSlug: p.id, examSlug: p.exam, paperSlug: p.paper }); if (!c?.exam || !c.paper) notFound(); const canonical = paperUrl(c.state.slug, c.exam.slug, c.paper.slug); if (c.usedAlias || p.id !== c.state.slug || p.exam !== c.exam.slug || p.paper !== c.paper.slug) permanentRedirect(canonical); const seo = resolveSeoFields(c.paper, { title: `${c.exam.name} ${c.paper.name} Mock Tests`, description: `Take free ${c.paper.name} mock tests for ${c.exam.name} in ${c.state.name}.` }); return <><JsonLd data={collectionStructuredData(seo.title, seo.description, canonical, [{ name: "Home", path: "/" }, { name: "Mock tests", path: "/mock-tests" }, { name: c.state.name, path: stateUrl(c.state.slug) }, { name: c.exam.name, path: examUrl(c.state.slug, c.exam.slug) }, { name: c.paper.name, path: canonical }])} />{await MockTestsPage({ searchParams: Promise.resolve({ ...(await searchParams), state: c.state.slug, exam: c.exam.slug, paper: c.paper.slug }), canonicalPath: canonical })}</>; }
