export const QUESTION_IMPORT_REQUIRED_HEADERS = [
  "import_key",
  "subject",
  "question_en",
  "option_a_en",
  "option_b_en",
  "option_c_en",
  "option_d_en",
  "question_te",
  "option_a_te",
  "option_b_te",
  "option_c_te",
  "option_d_te",
  "correct_answer",
] as const;

export const QUESTION_IMPORT_EXPORT_HEADERS = [
  "import_key",
  "subject",
  "question_en",
  "option_a_en",
  "option_b_en",
  "option_c_en",
  "option_d_en",
  "explanation_en",
  "question_te",
  "option_a_te",
  "option_b_te",
  "option_c_te",
  "option_d_te",
  "explanation_te",
  "correct_answer",
  "image_url",
  "source_reference",
  "source_exam_date",
  "difficulty",
  "is_active",
  "content_lifecycle",
  "review_on",
  "expires_on",
  "question_order",
  "marks",
  "negative_marks",
] as const;

